# Generated by Django 2.0.4 on 2018-05-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'new',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('pic_url', models.AutoField(primary_key=True, serialize=False)),
                ('pic_bin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
